services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    env_file: .env
    volumes:
      - /home/matesant/data/wordpress:/var/www/wordpress
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - inception


  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - /home/matesant/data/wordpress:/var/www/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wp", "core", "is-installed", "--allow-root"]
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - inception


  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - /home/matesant/data/mariadb:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3


networks:
  inception:
    driver: bridge