services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    env_file: .env
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception


  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - inception


  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: 
      always
    env_file: 
      .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception


volumes:
  mariadb_data:
    driver: local
    driver_opts:
        type: none
        device: /home/${USER}/data/mariadb
        o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind
  certs:

networks:
  inception:
    driver: bridge