services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    env_file: .env
    volumes:
      - /home/matesant/data/wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception


  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - /home/matesant/data/wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - inception


  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: 
      always
    env_file: 
      .env
    volumes:
      - /home/matesant/data/mariadb:/var/lib/mysql
    networks:
      - inception


networks:
  inception:
    driver: bridge