version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
      - certs:/etc/nginx/certs
    networks:
      - inception
    depends_on:
        - wordpress
    restart: always
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env

volumes:
  db_data:
  wordpress_data:
  certs:

networks:
  inception:
    driver: bridge